// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package handlers

// Currency defines model for Currency.
type Currency struct {
	AddressValidation string    `json:"addressValidation"`
	Available         bool      `json:"available"`
	Image             string    `json:"image"`
	Name              string    `json:"name"`
	Networks          []Network `json:"networks"`
	Price             float64   `json:"price"`
	Symbol            string    `json:"symbol"`
}

// Network defines model for Network.
type Network struct {
	Name string `json:"name"`
}

// Quote defines model for Quote.
type Quote struct {
	Amount float64 `json:"amount"`
	From   string  `json:"from"`
	To     string  `json:"to"`
}

// Symbol defines model for Symbol.
type Symbol = string

// GetV1CurrenciesParams defines parameters for GetV1Currencies.
type GetV1CurrenciesParams struct {
	// Name Name of the currency
	Name *Symbol `form:"name,omitempty" json:"name,omitempty"`

	// Popular Popular currencies
	Popular *bool `form:"popular,omitempty" json:"popular,omitempty"`

	// Active Active currencies
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// Symbols Symbols
	Symbols *[]string `form:"symbols,omitempty" json:"symbols,omitempty"`
}

// GetV1QuoteParams defines parameters for GetV1Quote.
type GetV1QuoteParams struct {
	// From From currency
	From Symbol `form:"from" json:"from"`

	// To To currency
	To Symbol `form:"to" json:"to"`

	// Amount Amount
	Amount float64 `form:"amount" json:"amount"`
}
