// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get currencies
	// (GET /v1/currencies)
	GetV1Currencies(c *gin.Context, params GetV1CurrenciesParams)
	// Get quote
	// (GET /v1/quote)
	GetV1Quote(c *gin.Context, params GetV1QuoteParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetV1Currencies operation middleware
func (siw *ServerInterfaceWrapper) GetV1Currencies(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1CurrenciesParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "popular" -------------

	err = runtime.BindQueryParameter("form", true, false, "popular", c.Request.URL.Query(), &params.Popular)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter popular: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameter("form", true, false, "active", c.Request.URL.Query(), &params.Active)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter active: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "symbols" -------------

	err = runtime.BindQueryParameter("form", true, false, "symbols", c.Request.URL.Query(), &params.Symbols)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter symbols: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Currencies(c, params)
}

// GetV1Quote operation middleware
func (siw *ServerInterfaceWrapper) GetV1Quote(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1QuoteParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", c.Request.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", c.Request.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "amount" -------------

	if paramValue := c.Query("amount"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument amount is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "amount", c.Request.URL.Query(), &params.Amount)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter amount: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Quote(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si any) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, siAny any, optionsAny any) {
	si := siAny.(ServerInterface)
	options := optionsAny.(GinServerOptions)

	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/currencies", wrapper.GetV1Currencies)

	router.GET(options.BaseURL+"/v1/quote", wrapper.GetV1Quote)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xVS2/bMAz+K4HW21zbXXfofFpRYEMxrA+06KXIAMZhEnXWI5ScIivy3wdJfiV2mg7d",
	"zRbJj6T48dMLy5XQSqK0hmUvzOQLFOA/L0oilPnafWtSGsly9BaYTgmNeYCCT8FyJd2hXWtkGTOWuJyz",
	"TcRgBbyASYEd60SpAkE6Mxcwx8FACWKPAe2zot++Bm5R+I8jwhnL2IekbSSpukiuQoCLrcCACNbuXxPP",
	"fZaZIgGWZWyqSlds4ypLMUFyvmYtJqoYKGkTMcJlyQmnLHsMhTfudYvdm6jzRgN32Olv3BShJk+YW1dE",
	"3UtvGnuua6i2IdzbUlkcmLFQpbRvvKAZKTE4MasOV+aDvWtUZx2q864ZggZrkSTL2K9HOP6THn8Zfzxq",
	"y2rSOJLJma8gV9JC7ttBAbxgWX301XC9UDI2z6BZzT125w9Hd+GwJBewsFabLEm6AZuITdHkxHVYgzrQ",
	"GUfnN5csYgXPURpsJ8V+Xt73QJVGaVRJOcaK5kkVZBLn6+6R2wL78KPj0bVG6b5O45RFbIVkQiEncRqn",
	"LtQhg+YsY6dxGn92FAS78DNOVidJHra8mvoc/R1t9/Qd7ajj5iHJc/ZyGswPJxdduwYCgRbJsOxxF+0K",
	"BI7UbGQXWKOu3a4427JEWrdTqPfJb/OhXa/4sdlEuxlvlC4LoO0ehvLp4LiVcle4+vDnueUrPIwO3u8f",
	"wUNX+yBNY20xG2HsL+OWBG7Gbg2NVo5nzv9TmtargmHzQeuC537SyZMJMj+Q6LWpNI9IP39vd65/eG0w",
	"pRBA6z7xnNFRdlkr1l62Bo9Bot5Wplc5+o2UOETOSrZaJbNU4vvJeq8OJfZC+b/Tngfh3cPc2rg/a/+R",
	"EFxyUQqWpb0H493Ue63HMOC30mvZehukVU2HVpyzJClUDsVCGZudpWdOU192xBs0j7deBfd+wXyIWVs6",
	"WV1vl+Ljzd8AAAD//0QQxVKSCQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
